container: bazarr
image: ghcr.io/hotio/bazarr
tag: latest
restart: always

ports:
  - "6767:6767"

env:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  TZ: "America/Monterrey"
  WEBUI_PORTS: "6767/tcp,6767/udp"

volumes:
  - "/home/docker/bazarr/config:/config"
  - "/media/Media/Movies:/Movies"
  - "/media/Media/MyMovies:/MyMovies"
  - "/media/Media/TVShows:/TVShows"
  - "/media/Media/MyTVShows:/MyTVShows"
