container: prowlarr
image: lscr.io/linuxserver/prowlarr
tag: latest
restart: always

ports:
  - "9696:9696"

env:
  PUID: "1000"
  PGID: "1000"
  UMASK: "002"
  TZ: "America/Monterrey"

volumes:
  - "/home/docker/prowlarr/config:/config"
